import Foundation

enum MockCatalogData {

    // MARK: - Model Catalog
    // App Store catalog: keep only models with green working status in this app runtime.

    static let items: [ModelCatalogItem] = [
        ModelCatalogItem(
            displayName: "Apple Intelligence",
            family: .appleIntelligence,
            provider: .localFile,
            variant: "System Foundation Model",
            summary: "Apple's on-device Foundation Models runtime. Uses the system Apple Intelligence language model when available; no separate model weights are downloaded by this app.",
            parameterSize: "~3B system model",
            quantization: "System managed",
            diskSize: "System managed",
            contextWindow: "System",
            runtimeType: .foundationModels,
            supportsReasoning: true,
            supportsToolCalling: false,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .pro
        ),

        ModelCatalogItem(
            displayName: "Granite 3.3 2B Instruct (MLX)",
            family: .granite,
            variant: "4-bit MLX",
            summary: "IBM Granite 3.3 instruct model converted by MLX Community. Text-only local chat model with Apache 2.0 licensing and a practical memory footprint for iPhone.",
            parameterSize: "2B",
            quantization: "MLX 4-bit",
            diskSize: "~1.4 GB",
            contextWindow: "128K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/granite-3.3-2b-instruct-4bit",
            supportsReasoning: true,
            supportsToolCalling: true,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .standard
        ),

        ModelCatalogItem(
            id: UUID(uuidString: "671E127B-1ED4-59C5-A93F-A8730A25EAF3"),
            displayName: "Gemma 4 E2B Instruct (LiteRT-LM)",
            family: .gemma,
            variant: "LiteRT-LM · Vision",
            summary: "Google Gemma 4 edge-sized instruct model using the LiteRT-LM package for stable on-device image and text inference.",
            parameterSize: "2B",
            quantization: "LiteRT-LM INT4",
            diskSize: "2.58 GB",
            contextWindow: "128K",
            downloadURL: URL(string: "https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm/resolve/main/gemma-4-E2B-it.litertlm"),
            runtimeType: .liteRTLM,
            sourceSupportsVision: true,
            supportsVision: true,
            supportsReasoning: true,
            supportsToolCalling: true,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .pro,
            inputModes: [.text, .image, .document]
        ),
        ModelCatalogItem(
            id: UUID(uuidString: "9BD7F8CA-E895-5B96-8718-0BB5CB7FC186"),
            displayName: "Gemma 4 E4B Instruct (LiteRT-LM)",
            family: .gemma,
            variant: "LiteRT-LM · Vision",
            summary: "Larger Gemma 4 instruct variant using the LiteRT-LM package for local chat and image understanding on Pro-tier iPhones.",
            parameterSize: "4B",
            quantization: "LiteRT-LM INT4",
            diskSize: "3.66 GB",
            contextWindow: "128K",
            downloadURL: URL(string: "https://huggingface.co/litert-community/gemma-4-E4B-it-litert-lm/resolve/main/gemma-4-E4B-it.litertlm"),
            runtimeType: .liteRTLM,
            sourceSupportsVision: true,
            supportsVision: false,
            supportsReasoning: true,
            supportsToolCalling: true,
            runtimeStatus: .worksWithWarnings,
            auditVerdict: .yellow("image-runtime-failed-xnnpack-allocation-on-device-text-only"),
            testedDeviceTier: .pro,
            minimumTier: .pro,
            inputModes: [.text, .document]
        ),
        ModelCatalogItem(
            id: UUID(uuidString: "150BD022-A9BC-5625-8D84-EA08E6578B95"),
            displayName: "Gemma 2 2B Instruct (MLX)",
            family: .gemma,
            variant: "4-bit MLX",
            summary: "Earlier Gemma 2 instruct model converted for MLX. Text-only local chat model with a moderate footprint.",
            parameterSize: "2B",
            quantization: "MLX 4-bit",
            diskSize: "~1.6 GB",
            contextWindow: "8K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/gemma-2-2b-it-4bit",
            supportsReasoning: true,
            supportsToolCalling: false,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .standard
        ),
        ModelCatalogItem(
            id: UUID(uuidString: "2D1A8162-56B2-530A-AC76-ACBDF74B61AB"),
            displayName: "Gemma 3 1B Instruct (MLX)",
            family: .gemma,
            variant: "4-bit MLX",
            summary: "Compact Gemma 3 instruct model converted by MLX Community. Device audit completed, but output can include repeated filler and fabricated source links.",
            parameterSize: "1B",
            quantization: "MLX 4-bit",
            diskSize: "~700 MB",
            contextWindow: "32K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/gemma-3-1b-it-4bit",
            supportsReasoning: true,
            supportsToolCalling: false,
            runtimeStatus: .worksWithWarnings,
            auditVerdict: .yellow("audited-noisy-output-fabricated-sources"),
            testedDeviceTier: .pro,
            minimumTier: .standard
        ),

        ModelCatalogItem(
            displayName: "Llama 3.2 1B Instruct (MLX)",
            family: .llama,
            variant: "4-bit MLX",
            summary: "Meta Llama 3.2 compact instruct model, surfaced as a built-in local chat option for fast private conversations.",
            parameterSize: "1B",
            quantization: "MLX 4-bit",
            diskSize: "~0.8 GB",
            contextWindow: "128K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/Llama-3.2-1B-Instruct-4bit",
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .standard
        ),

        ModelCatalogItem(
            displayName: "Phi 3.5 Mini Instruct (MLX)",
            family: .phi,
            variant: "4-bit MLX",
            summary: "Microsoft Phi compact assistant model for local chat and coding-style prompts on newer iPhones.",
            parameterSize: "3.8B",
            quantization: "MLX 4-bit",
            diskSize: "~2.3 GB",
            contextWindow: "128K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/Phi-3.5-mini-instruct-4bit",
            supportsReasoning: true,
            runtimeStatus: .worksWithWarnings,
            auditVerdict: .yellow("built-in-provider-model-pending-full-device-audit"),
            minimumTier: .pro
        ),

        ModelCatalogItem(
            displayName: "DeepSeek R1 Distill Qwen 1.5B (MLX)",
            family: .deepSeek,
            variant: "4-bit MLX · Reasoning",
            summary: "DeepSeek R1 distilled Qwen model for small local reasoning workflows without leaving the device.",
            parameterSize: "1.5B",
            quantization: "MLX 4-bit",
            diskSize: "~1.0 GB",
            contextWindow: "32K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/DeepSeek-R1-Distill-Qwen-1.5B-4bit",
            supportsReasoning: true,
            isThinkingModel: true,
            runtimeStatus: .worksWithWarnings,
            auditVerdict: .yellow("built-in-provider-model-pending-full-device-audit"),
            minimumTier: .standard
        ),

        ModelCatalogItem(
            displayName: "Ministral 3 3B Instruct (MLX)",
            family: .mistral,
            variant: "4-bit MLX",
            summary: "Mistral-family 3B instruct model for a built-in European open-weight local chat lane.",
            parameterSize: "3B",
            quantization: "MLX 4-bit",
            diskSize: "~2.2 GB",
            contextWindow: "128K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/Ministral-3-3B-Instruct-2512-4bit",
            supportsReasoning: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .pro
        ),

        ModelCatalogItem(
            displayName: "Qwen 3.5 VL 0.8B (MLX)",
            family: .qwen,
            variant: "4-bit MLX · Vision",
            summary: "Compact Qwen 3.5 vision-language model. Image input passed the iPhone 17 Pro vision probe with the VLM-safe generation path.",
            parameterSize: "0.8B",
            quantization: "MLX 4-bit",
            diskSize: "~1.0 GB",
            contextWindow: "256K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/Qwen3.5-0.8B-4bit",
            sourceSupportsVision: true,
            supportsVision: true,
            supportsToolCalling: true,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .pro
        ),
        ModelCatalogItem(
            displayName: "Qwen 3.5 VL 4B (MLX)",
            family: .qwen,
            variant: "4-bit MLX · Vision",
            summary: "Qwen 3.5 4B vision-language model for stronger image and document understanding on recent iPhones.",
            parameterSize: "4B",
            quantization: "MLX 4-bit",
            diskSize: "~3.0 GB",
            contextWindow: "256K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/Qwen3.5-4B-4bit",
            sourceSupportsVision: true,
            supportsVision: false,
            supportsToolCalling: true,
            runtimeStatus: .worksWithWarnings,
            auditVerdict: .yellow("image-prefill-memory-killed-on-device-text-only"),
            testedDeviceTier: .pro,
            minimumTier: .pro
        ),
        ModelCatalogItem(
            displayName: "Qwen 3 0.6B (MLX)",
            family: .qwen,
            variant: "4-bit MLX",
            summary: "Ultra-compact Qwen 3 text model on Apple Silicon. Native thinking with a small memory footprint for fast on-device chat.",
            parameterSize: "0.6B",
            quantization: "MLX 4-bit",
            diskSize: "~0.6 GB",
            contextWindow: "40K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/Qwen3-0.6B-4bit",
            supportsReasoning: true,
            isThinkingModel: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .compact
        ),
        ModelCatalogItem(
            displayName: "Qwen 3 1.7B (MLX)",
            family: .qwen,
            variant: "4-bit MLX",
            summary: "Compact Qwen 3 text model on Apple Silicon. Good balance of speed and quality for local chat with native thinking.",
            parameterSize: "1.7B",
            quantization: "MLX 4-bit",
            diskSize: "~1.7 GB",
            contextWindow: "40K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/Qwen3-1.7B-4bit",
            supportsReasoning: true,
            isThinkingModel: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .standard
        ),
        ModelCatalogItem(
            displayName: "Qwen 3 4B 2507 Instruct (GGUF)",
            family: .qwen,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Latest Qwen 3 4B instruct release for the llama.cpp lane. Text-only on this runtime path, but aligned for tool calling and long-context local chat.",
            parameterSize: "4B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~2.5 GB",
            contextWindow: "256K",
            downloadURL: URL(string: "https://huggingface.co/unsloth/Qwen3-4B-Instruct-2507-GGUF/resolve/main/Qwen3-4B-Instruct-2507-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsReasoning: true,
            supportsToolCalling: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .pro
        ),
        ModelCatalogItem(
            displayName: "Qwen 3 4B 2507 Thinking (GGUF)",
            family: .qwen,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Latest Qwen 3 4B thinking release for the llama.cpp lane. Ideal when you want newer reasoning behavior without leaving the on-device GGUF path.",
            parameterSize: "4B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~2.5 GB",
            contextWindow: "256K",
            downloadURL: URL(string: "https://huggingface.co/unsloth/Qwen3-4B-Thinking-2507-GGUF/resolve/main/Qwen3-4B-Thinking-2507-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsReasoning: true,
            supportsToolCalling: true,
            isThinkingModel: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .pro
        ),

        ModelCatalogItem(
            displayName: "LFM2.5 VL 1.6B (MLX)",
            family: .lfm,
            variant: "4-bit MLX · Vision",
            summary: "Liquid LFM2.5 vision-language model. Image input passed the iPhone 17 Pro vision probe.",
            parameterSize: "1.6B",
            quantization: "MLX 4-bit",
            diskSize: "~1.5 GB",
            contextWindow: "32K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/LFM2.5-VL-1.6B-4bit",
            sourceSupportsVision: true,
            supportsVision: true,
            supportsToolCalling: true,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .pro
        ),
        ModelCatalogItem(
            displayName: "LFM2.5 350M (MLX)",
            family: .lfm,
            variant: "6-bit MLX · Latest",
            summary: "Latest lightweight LFM2.5 release optimized for low-memory edge instruction following. Uses the LFM ChatML prompt path in this app.",
            parameterSize: "350M",
            quantization: "MLX 6-bit",
            diskSize: "~0.4 GB",
            contextWindow: "32K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/LFM2.5-350M-6bit",
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .compact
        ),
        ModelCatalogItem(
            displayName: "LFM2.5 1.2B Thinking (MLX)",
            family: .lfm,
            variant: "6-bit MLX · Latest",
            summary: "Latest LFM2.5 reasoning-focused release for on-device planning and deeper local reasoning.",
            parameterSize: "1.2B",
            quantization: "MLX 6-bit",
            diskSize: "~1.0 GB",
            contextWindow: "32K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/LFM2.5-1.2B-Thinking-6bit",
            supportsReasoning: true,
            isThinkingModel: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .standard
        ),
        ModelCatalogItem(
            displayName: "LFM2.5 1.2B Instruct (MLX)",
            family: .lfm,
            variant: "4-bit MLX",
            summary: "Liquid Foundation 2.5 text-only model on Apple Silicon. Optimized for chat, instruction following, RAG, and tool-calling tasks.",
            parameterSize: "1.2B",
            quantization: "MLX 4-bit",
            diskSize: "~0.7 GB",
            contextWindow: "32K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/LFM2.5-1.2B-Instruct-4bit",
            supportsToolCalling: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .standard
        ),

        // MARK: - New Edge Models
        ModelCatalogItem(
            displayName: "LFM2.5 230M Instruct (MLX)",
            family: .lfm,
            variant: "6-bit MLX · Latest",
            summary: "Latest Liquid LFM2.5 230M model. Ultra-compact and highly optimized for local tool calling and agentic workflows.",
            parameterSize: "230M",
            quantization: "MLX 6-bit",
            diskSize: "~180 MB",
            contextWindow: "32K",
            runtimeType: .mlx,
            mlxModelID: "LiquidAI/LFM2.5-230M-MLX-6bit",
            supportsToolCalling: true,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .compact
        ),
        ModelCatalogItem(
            displayName: "LFM2.5 230M Instruct (GGUF)",
            family: .lfm,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Latest Liquid LFM2.5 230M model in GGUF format. Extremely lightweight with strong tool calling.",
            parameterSize: "230M",
            quantization: "GGUF Q4_K_M",
            diskSize: "~153 MB",
            contextWindow: "32K",
            downloadURL: URL(string: "https://huggingface.co/LiquidAI/LFM2.5-230M-GGUF/resolve/main/LFM2.5-230M-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsToolCalling: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .compact
        ),
        ModelCatalogItem(
            displayName: "LFM2.5 1.2B Instruct (GGUF)",
            family: .lfm,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Liquid LFM2.5 1.2B instruct model in GGUF format. Balanced on-device general instruction follower.",
            parameterSize: "1.2B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~731 MB",
            contextWindow: "32K",
            downloadURL: URL(string: "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-GGUF/resolve/main/LFM2.5-1.2B-Instruct-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsToolCalling: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .standard
        ),

        ModelCatalogItem(
            displayName: "Gemma 3 270M Instruct (MLX)",
            family: .gemma,
            variant: "4-bit MLX",
            summary: "Google Gemma 3 ultra-lightweight 270M instruct model. Perfect for fast on-device chat on standard devices.",
            parameterSize: "270M",
            quantization: "MLX 4-bit",
            diskSize: "~150 MB",
            contextWindow: "32K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/gemma-3-270m-it-4bit",
            supportsReasoning: true,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .compact
        ),
        ModelCatalogItem(
            id: UUID(uuidString: "A9A9D0A8-C083-49F1-8B8D-28D8A0F2B0B0"),
            displayName: "Gemma 4 E2B Instruct (MLX)",
            family: .gemma,
            variant: "4-bit MLX · Vision",
            summary: "Google Gemma 4 2B instruct model converted to MLX. Outstanding on-device capability with native vision understanding.",
            parameterSize: "2B",
            quantization: "MLX 4-bit",
            diskSize: "~1.5 GB",
            contextWindow: "128K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/gemma-4-e2b-it-4bit",
            sourceSupportsVision: true,
            supportsVision: true,
            supportsReasoning: true,
            supportsToolCalling: true,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .pro
        ),
        ModelCatalogItem(
            displayName: "Gemma 4 E2B Instruct (GGUF)",
            family: .gemma,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Latest Google Gemma 4 2B instruct model in GGUF format for llama.cpp runtime.",
            parameterSize: "2B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~3.4 GB",
            contextWindow: "128K",
            downloadURL: URL(string: "https://huggingface.co/unsloth/gemma-4-E2B-it-GGUF/resolve/main/gemma-4-E2B-it-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsReasoning: true,
            supportsToolCalling: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .pro
        ),

        ModelCatalogItem(
            displayName: "Qwen 3.5 2B Instruct (MLX)",
            family: .qwen,
            variant: "4-bit MLX · Vision",
            summary: "Alibaba Qwen 3.5 2B instruction-tuned VLM model converted to MLX. Strong multimodal and long-context capabilities.",
            parameterSize: "2B",
            quantization: "MLX 4-bit",
            diskSize: "~1.4 GB",
            contextWindow: "256K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/Qwen3.5-2B-MLX-4bit",
            sourceSupportsVision: true,
            supportsVision: true,
            supportsReasoning: true,
            supportsToolCalling: true,
            isThinkingModel: true,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .pro
        ),
        ModelCatalogItem(
            displayName: "Qwen 3.5 0.8B Instruct (GGUF)",
            family: .qwen,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Latest Alibaba Qwen 3.5 0.8B instruction-tuned model in GGUF format for local edge inference.",
            parameterSize: "0.8B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~0.6 GB",
            contextWindow: "256K",
            downloadURL: URL(string: "https://huggingface.co/unsloth/Qwen3.5-0.8B-GGUF/resolve/main/Qwen3.5-0.8B-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsReasoning: true,
            supportsToolCalling: true,
            isThinkingModel: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .compact
        ),
        ModelCatalogItem(
            displayName: "Qwen 3.5 2B Instruct (GGUF)",
            family: .qwen,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Latest Alibaba Qwen 3.5 2B instruction-tuned model in GGUF format.",
            parameterSize: "2B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~1.3 GB",
            contextWindow: "256K",
            downloadURL: URL(string: "https://huggingface.co/unsloth/Qwen3.5-2B-GGUF/resolve/main/Qwen3.5-2B-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsReasoning: true,
            supportsToolCalling: true,
            isThinkingModel: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .standard
        ),
        ModelCatalogItem(
            displayName: "Qwen 3.5 4B Instruct (GGUF)",
            family: .qwen,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Latest Alibaba Qwen 3.5 4B instruction-tuned model in GGUF format.",
            parameterSize: "4B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~2.6 GB",
            contextWindow: "256K",
            downloadURL: URL(string: "https://huggingface.co/unsloth/Qwen3.5-4B-GGUF/resolve/main/Qwen3.5-4B-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsReasoning: true,
            supportsToolCalling: true,
            isThinkingModel: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .pro
        ),
        ModelCatalogItem(
            displayName: "Qwen 3 4B 2507 Instruct (MLX)",
            family: .qwen,
            variant: "4-bit MLX",
            summary: "Alibaba Qwen 3 4B instruction-tuned model converted to MLX. Strong reasoning and general chat capability.",
            parameterSize: "4B",
            quantization: "MLX 4-bit",
            diskSize: "~2.4 GB",
            contextWindow: "256K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/Qwen3-4B-Instruct-2507-4bit",
            supportsReasoning: true,
            supportsToolCalling: true,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .pro
        ),
        ModelCatalogItem(
            displayName: "Qwen 3 4B 2507 Thinking (MLX)",
            family: .qwen,
            variant: "4-bit MLX · Reasoning",
            summary: "Alibaba Qwen 3 4B thinking model converted to MLX. Native reasoning block with thinking tags.",
            parameterSize: "4B",
            quantization: "MLX 4-bit",
            diskSize: "~2.4 GB",
            contextWindow: "256K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/Qwen3-4B-Thinking-2507-4bit",
            supportsReasoning: true,
            supportsToolCalling: true,
            isThinkingModel: true,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .pro
        ),

        ModelCatalogItem(
            displayName: "Granite 3.3 2B Instruct (GGUF)",
            family: .granite,
            variant: "Q4_K_M GGUF · Latest",
            summary: "IBM Granite 3.3 2B instruct model in GGUF format for llama.cpp runtime.",
            parameterSize: "2B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~1.4 GB",
            contextWindow: "128K",
            downloadURL: URL(string: "https://huggingface.co/ibm-granite/granite-3.3-2b-instruct-GGUF/resolve/main/granite-3.3-2b-instruct-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsReasoning: true,
            supportsToolCalling: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .standard
        ),

        ModelCatalogItem(
            displayName: "Llama 3.2 3B Instruct (MLX)",
            family: .llama,
            variant: "4-bit MLX",
            summary: "Meta Llama 3.2 3B instruct model converted to MLX. Strong instruction-following performance.",
            parameterSize: "3B",
            quantization: "MLX 4-bit",
            diskSize: "~2.0 GB",
            contextWindow: "128K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/Llama-3.2-3B-Instruct-4bit",
            supportsReasoning: true,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .pro
        ),
        ModelCatalogItem(
            displayName: "Llama 3.2 1B Instruct (GGUF)",
            family: .llama,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Meta Llama 3.2 compact 1B instruct model in GGUF format for llama.cpp.",
            parameterSize: "1B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~0.8 GB",
            contextWindow: "128K",
            downloadURL: URL(string: "https://huggingface.co/unsloth/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .standard
        ),
        ModelCatalogItem(
            displayName: "Llama 3.2 3B Instruct (GGUF)",
            family: .llama,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Meta Llama 3.2 3B instruct model in GGUF format for llama.cpp runtime.",
            parameterSize: "3B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~2.0 GB",
            contextWindow: "128K",
            downloadURL: URL(string: "https://huggingface.co/unsloth/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsReasoning: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .pro
        ),

        ModelCatalogItem(
            displayName: "Phi 4 Mini Instruct (MLX)",
            family: .phi,
            variant: "4-bit MLX",
            summary: "Microsoft Phi 4 Mini 3.8B model converted to MLX. Exceptionally high reasoning performance for its size.",
            parameterSize: "3.8B",
            quantization: "MLX 4-bit",
            diskSize: "~2.3 GB",
            contextWindow: "128K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/Phi-4-mini-instruct-4bit",
            supportsReasoning: true,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .pro
        ),
        ModelCatalogItem(
            displayName: "Phi 4 Mini Instruct (GGUF)",
            family: .phi,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Microsoft Phi 4 Mini 3.8B model in GGUF format for llama.cpp runtime.",
            parameterSize: "3.8B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~2.3 GB",
            contextWindow: "128K",
            downloadURL: URL(string: "https://huggingface.co/unsloth/Phi-4-mini-instruct-GGUF/resolve/main/Phi-4-mini-instruct-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsReasoning: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .pro
        ),
        ModelCatalogItem(
            displayName: "Phi 3.5 Mini Instruct (GGUF)",
            family: .phi,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Microsoft Phi 3.5 Mini 3.8B model in GGUF format for llama.cpp runtime.",
            parameterSize: "3.8B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~2.3 GB",
            contextWindow: "128K",
            downloadURL: URL(string: "https://huggingface.co/unsloth/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsReasoning: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .pro
        ),

        ModelCatalogItem(
            displayName: "Ministral 3 3B Instruct (GGUF)",
            family: .mistral,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Ministral-family 3B instruct model in GGUF format for local edge inference.",
            parameterSize: "3B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~2.3 GB",
            contextWindow: "128K",
            downloadURL: URL(string: "https://huggingface.co/unsloth/Ministral-3-3B-Instruct-2512-GGUF/resolve/main/Ministral-3-3B-Instruct-2512-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsReasoning: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .pro
        ),

        ModelCatalogItem(
            displayName: "DeepSeek R1 Distill Qwen 1.5B (GGUF)",
            family: .deepSeek,
            variant: "Q4_K_M GGUF · Latest",
            summary: "DeepSeek R1 distilled Qwen 1.5B reasoning model in GGUF format. Local reasoning on device with thinking tags.",
            parameterSize: "1.5B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~1.0 GB",
            contextWindow: "32K",
            downloadURL: URL(string: "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-1.5B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            supportsReasoning: true,
            isThinkingModel: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .standard
        ),

        ModelCatalogItem(
            displayName: "SmolLM2 1.7B Instruct (MLX)",
            family: .smolLM,
            variant: "4-bit MLX",
            summary: "Hugging Face SmolLM2 1.7B instruct model. Outstanding performance for general lightweight chat.",
            parameterSize: "1.7B",
            quantization: "MLX 4-bit",
            diskSize: "~1.0 GB",
            contextWindow: "8K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/SmolLM2-1.7B-Instruct",
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .standard
        ),
        ModelCatalogItem(
            displayName: "SmolLM2 1.7B Instruct (GGUF)",
            family: .smolLM,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Hugging Face SmolLM2 1.7B instruct model in GGUF format.",
            parameterSize: "1.7B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~1.0 GB",
            contextWindow: "8K",
            downloadURL: URL(string: "https://huggingface.co/unsloth/SmolLM2-1.7B-Instruct-GGUF/resolve/main/SmolLM2-1.7B-Instruct-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .standard
        ),
        ModelCatalogItem(
            displayName: "SmolVLM2 500M Instruct (MLX)",
            family: .smolVLM,
            variant: "8-bit MLX · Vision",
            summary: "Hugging Face SmolVLM2 500M vision-language model. Extremely lightweight image and video understanding.",
            parameterSize: "500M",
            quantization: "MLX 8-bit",
            diskSize: "~1.0 GB",
            contextWindow: "8K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/SmolVLM2-500M-Video-Instruct-mlx",
            sourceSupportsVision: true,
            supportsVision: true,
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .pro
        ),

        ModelCatalogItem(
            displayName: "StableLM 2 Zephyr 1.6B (MLX)",
            family: .stableLM,
            variant: "4-bit MLX",
            summary: "Stability AI StableLM 2 1.6B Zephyr model converted to MLX. Highly responsive chat assistant.",
            parameterSize: "1.6B",
            quantization: "MLX 4-bit",
            diskSize: "~1.0 GB",
            contextWindow: "8K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/stablelm-2-zephyr-1_6b-4bit",
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .standard
        ),
        ModelCatalogItem(
            displayName: "StableLM 2 Zephyr 1.6B (GGUF)",
            family: .stableLM,
            variant: "Q4_K_M GGUF · Latest",
            summary: "Stability AI StableLM 2 1.6B Zephyr model in GGUF format.",
            parameterSize: "1.6B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~1.0 GB",
            contextWindow: "8K",
            downloadURL: URL(string: "https://huggingface.co/second-state/stablelm-2-zephyr-1.6b-GGUF/resolve/main/stablelm-2-zephyr-1.6b-Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .standard
        ),

        ModelCatalogItem(
            displayName: "TinyLlama 1.1B Chat (MLX)",
            family: .tinyLlama,
            variant: "4-bit MLX",
            summary: "Compact 1.1B parameters chat assistant optimized for standard edge devices.",
            parameterSize: "1.1B",
            quantization: "MLX 4-bit",
            diskSize: "~600 MB",
            contextWindow: "2K",
            runtimeType: .mlx,
            mlxModelID: "mlx-community/TinyLlama-1.1B-Chat-v1.0",
            recommendedForIPhone: true,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            testedDeviceTier: .pro,
            minimumTier: .standard
        ),
        ModelCatalogItem(
            displayName: "TinyLlama 1.1B Chat (GGUF)",
            family: .tinyLlama,
            variant: "Q4_K_M GGUF · Latest",
            summary: "TinyLlama 1.1B Chat model in GGUF format for llama.cpp runtime.",
            parameterSize: "1.1B",
            quantization: "GGUF Q4_K_M",
            diskSize: "~640 MB",
            contextWindow: "2K",
            downloadURL: URL(string: "https://huggingface.co/second-state/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/TinyLlama-1.1B-Chat-v1.0.Q4_K_M.gguf?download=true"),
            runtimeType: .gguf,
            runtimeStatus: .recommended,
            auditVerdict: .green,
            minimumTier: .standard
        ),
    ]

    static let installedModels: [InstalledModel] = []

    static let citations: [SearchCitation] = [
        SearchCitation(
            title: "Example source",
            url: URL(string: "https://example.com/live-source")!,
            snippet: "Fresh web context should be clearly separated from local model output."
        )
    ]

    static let sessions: [ChatSession] = []

    // MARK: - All unique labs for filtering
    static let allLabs: [String] = {
        var seen = Set<String>()
        var labs: [String] = []
        for item in items {
            let lab = item.family.lab
            if !seen.contains(lab) {
                seen.insert(lab)
                labs.append(lab)
            }
        }
        return labs
    }()
}
